#!/bin/bash
# create_pr.sh - Create draft PR for AI-generated patch
# Usage: ./create_pr.sh --run-id <id> --issue <number> --repo <url>

set -euo pipefail

# Parse args
RUN_ID=""
ISSUE_NUM=""
REPO_URL=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --run-id) RUN_ID="$2"; shift 2 ;;
        --issue) ISSUE_NUM="$2"; shift 2 ;;
        --repo) REPO_URL="$2"; shift 2 ;;
        *) echo "Unknown: $1"; exit 1 ;;
    esac
done

[[ -z "$RUN_ID" ]] || [[ -z "$ISSUE_NUM" ]] || [[ -z "$REPO_URL" ]] && {
    echo "Usage: $0 --run-id <id> --issue <num> --repo <url>"
    exit 1
}

PATCH_FILE="data/patches/issue-${ISSUE_NUM}/fix.patch"
ARTIFACTS_DIR="data/runs/${RUN_ID}"
BRANCH="ai/fix-issue-${ISSUE_NUM}"

[[ ! -f "$PATCH_FILE" ]] && { echo "Patch not found: $PATCH_FILE"; exit 1; }

# Clone repo if needed
REPO_NAME=$(basename "$REPO_URL" .git)
REPO_DIR="/tmp/${REPO_NAME}-pr"

if [[ ! -d "$REPO_DIR" ]]; then
    git clone "$REPO_URL" "$REPO_DIR"
fi

cd "$REPO_DIR"

# Create branch
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

# Apply patch
git apply "../../../${PATCH_FILE}" || { echo "Failed to apply patch"; exit 1; }

# Commit
git add -A
git commit -m "Fix issue #${ISSUE_NUM} (AI-generated)

This patch was automatically generated by OpenFix.

Run ID: ${RUN_ID}
Artifacts: ${ARTIFACTS_DIR}

⚠️ AI Disclosure: This patch was generated by Gemini 2.5 Pro.
Please review carefully before merging."

# Push to fork (assumes origin is your fork)
git push -u origin "$BRANCH"

# Create draft PR
gh pr create \
    --draft \
    --title "Fix #${ISSUE_NUM} (AI-generated)" \
    --body "$(cat <<EOF
## AI-Generated Fix for Issue #${ISSUE_NUM}

This PR was automatically generated by OpenFix to address issue #${ISSUE_NUM}.

### 🤖 AI Disclosure
- **Model**: Gemini 2.5 Pro
- **Run ID**: \`${RUN_ID}\`
- **Generated**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

### 📊 Validation
See validation results in \`${ARTIFACTS_DIR}/validation.json\`

### 📝 Changes
\`\`\`diff
$(cat "../../../${PATCH_FILE}")
\`\`\`

### 🔍 Review Checklist
- [ ] Code changes are correct and safe
- [ ] Tests pass locally
- [ ] No security issues introduced
- [ ] Documentation updated if needed

**Please review carefully before merging.**
EOF
)"

echo "✓ Draft PR created for branch: $BRANCH"
